#!/bin/sh
uci -q batch <<-EOF >/dev/null
delete ucitrack.@sysmonitor[-1]
add ucitrack sysmonitor
set ucitrack.@sysmonitor[-1].init=sysmonitor
commit ucitrack
EOF

cat /etc/config/network | grep macaddr > null
if [ $? -eq 0 ];then
	uci set network.@device[1].macaddr=''
	uci set network.@device[1].name=''
	uci set network.@device[1]=''
	uci commit network
fi

cat > /etc/config/ttyd <<EOF
config ttyd
	option interface '@lan'
	option command '/bin/login'

config ttyd
	option interface '@wan'
	option command '/bin/login'
EOF

chmod 0600 /etc/dropbear/authorized_keys
chmod 0755 /etc/init.d/sysmonitor /usr/share/sysmonitor/*.sh
rm -rf /tmp/luci-modulecache /tmp/luci-indexcache

exit 0
